# See https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = 'clinvoice-match'
version = '0.5.4'
authors = ['Iron-E <code.iron.e@gmail.com>']
description = 'Strongly-typed match conditions for CLInvoice'

edition = '2021'
license = 'GPL3'
readme = 'README.md'
repository = 'https://www.github.com/Iron-E/clinvoice-match'

[dependencies]
clinvoice-error = {branch = 'release/0.3', git = 'https://github.com/Iron-E/clinvoice-error'}
clinvoice-finance = {branch = 'release/0.4', git = 'https://github.com/Iron-E/clinvoice-finance'}
clinvoice-schema = {branch = 'release/0.9', git = 'https://github.com/Iron-E/clinvoice-schema'}

humantime-serde = '1'
serde = {optional = true, version = "1"}
thiserror = '1'

[dev-dependencies]
pretty_assertions = "1"
regex = "1"
serde_yaml = "0.8"

[features]
default = []
serde = ["clinvoice-finance/serde", "serde/derive"]
